import { useState } from 'react';
import { Upload, FileCheck, ClipboardList, Info } from 'lucide-react';
import { api } from '../../services/api';

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:8000';

const STEPS = ['Upload image', 'Preview', 'Queue for review', 'Doctor review', 'Save to record'];

/**
 * Honest endoscopy-image workflow. There is no physical endoscope, ESP32 camera,
 * or device telemetry in this repository, so this page deliberately provides NO
 * live camera view, NO LED/zoom hardware controls, and NO device status.
 * Flow: upload a JPEG/PNG → preview → POST /api/v1/ai/analyze-image (stores +
 * queues for clinician review, returns no diagnosis) → doctor records findings
 * in the EMR via /medical-records.
 */
export default function LiveEndoscopeViewer() {
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState('');
  const [patientId, setPatientId] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState(null);
  const [finding, setFinding] = useState('');
  const [saved, setSaved] = useState('');

  const pick = (f) => {
    setError(''); setResult(null); setSaved('');
    if (!f) return;
    if (!['image/jpeg', 'image/png'].includes(f.type)) { setError('Only JPEG or PNG images are accepted.'); return; }
    if (f.size > 10 * 1024 * 1024) { setError('File is larger than 10 MB.'); return; }
    setFile(f);
    setPreview(URL.createObjectURL(f));
  };

  const submit = async () => {
    if (!file) return;
    setBusy(true); setError('');
    try {
      const token = localStorage.getItem('medicore_token');
      const fd = new FormData();
      fd.append('file', file);
      const qs = patientId ? `?patient_id=${encodeURIComponent(patientId)}` : '';
      const res = await fetch(`${API_BASE}/api/v1/ai/analyze-image${qs}`, {
        method: 'POST',
        headers: token ? { Authorization: `Bearer ${token}` } : {},
        body: fd,
      });
      if (!res.ok) throw new Error(await res.text());
      setResult(await res.json());
    } catch (e) {
      setError(typeof e?.message === 'string' ? e.message : 'Upload failed. Check that the API is running.');
    } finally { setBusy(false); }
  };

  const saveToRecord = async () => {
    if (!patientId || !finding.trim()) { setError('Patient ID and written findings are required to save to the record.'); return; }
    setBusy(true); setError('');
    try {
      await api.post('/api/v1/medical-records', {
        patient_id: patientId, diagnosis: finding.trim(),
        notes: `Endoscopy image review. Stored at ${result?.url || 'upload'}. No automated diagnosis was generated.`,
      });
      setSaved('Findings saved to the medical record.');
      setFinding('');
    } catch (e) {
      setError(e?.message || 'Could not save to the medical record.');
    } finally { setBusy(false); }
  };

  return (
    <div className="animate-fadeIn">
      <div className="clinical-header">
        <div>
          <p className="eyebrow eyebrow--pine">ENT Endoscopy · Image review workflow</p>
          <h1 style={{ marginTop: 8 }}>Endoscopy images</h1>
          <p className="page-subtitle">Upload → preview → queue for review → save findings to the record</p>
        </div>
        <span className="ai-flag">No endoscope hardware connected</span>
      </div>

      <div className="card" style={{ marginBottom: 16, display: 'flex', gap: 10, alignItems: 'flex-start' }}>
        <Info size={16} style={{ marginTop: 2, flexShrink: 0 }} />
        <p style={{ fontSize: '0.86rem', color: 'var(--text-secondary)', lineHeight: 1.6 }}>
          This system has no physical endoscope camera, ESP32 device, or automated diagnosis model.
          Images you upload are stored on the API server and queued for clinician review —
          <strong> no diagnosis or confidence score is generated by software</strong>.
        </p>
      </div>

      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 20 }}>
        {STEPS.map((s, i) => (
          <span key={s} className="badge" style={i === 0 ? { background: 'var(--pine)', color: '#F7F5EE', borderColor: 'var(--pine)' } : {}}>
            {i + 1}. {s}
          </span>
        ))}
      </div>

      <div className="grid-2">
        <div className="card">
          <div className="eyebrow" style={{ marginBottom: 12 }}>1 · Upload &amp; preview</div>
          <div className="form-group">
            <label className="form-label">Patient ID (required to save findings)</label>
            <input className="form-input" value={patientId} onChange={(e) => setPatientId(e.target.value)} placeholder="e.g. patient UUID from Patients page" />
          </div>
          <label className="btn" style={{ cursor: 'pointer' }}>
            <Upload size={15} /> Choose JPEG / PNG
            <input type="file" accept="image/jpeg,image/png" hidden onChange={(e) => pick(e.target.files?.[0])} />
          </label>
          {preview && (
            <div style={{ marginTop: 14 }}>
              <img src={preview} alt="Endoscopy upload preview" style={{ width: '100%', borderRadius: 8, border: '1px solid var(--border-color)' }} />
              <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)', marginTop: 8 }}>{file?.name} · {((file?.size || 0) / 1024).toFixed(0)} KB · preview only, not yet stored</p>
            </div>
          )}
          {error && <p style={{ color: 'var(--color-error)', fontSize: '0.85rem', marginTop: 12 }}>{error}</p>}
          <button className="btn btn-primary" style={{ marginTop: 14 }} disabled={!file || busy} onClick={submit}>
            {busy ? 'Uploading…' : 'Upload & queue for review'}
          </button>
        </div>

        <div className="card">
          <div className="eyebrow" style={{ marginBottom: 12 }}>2 · Intake result &amp; doctor review</div>
          {!result && <p style={{ fontSize: '0.88rem', color: 'var(--text-secondary)' }}>No image queued yet. The intake result will appear here with storage details — never a diagnosis.</p>}
          {result && (
            <div>
              <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 10 }}>
                <span className="badge badge-yellow">Queued for clinician review</span>
                <span className="badge">No automated diagnosis</span>
              </div>
              <div className="kv"><span>Stored at</span><span style={{ fontSize: '0.76rem' }}>{result.url}</span></div>
              <div className="kv"><span>Format</span><span>{result.format} · {(result.bytes / 1024).toFixed(0)} KB</span></div>
              <div className="kv"><span>Diagnosis by software</span><span>None — not configured</span></div>
              <div className="form-group" style={{ marginTop: 14 }}>
                <label className="form-label"><ClipboardList size={12} style={{ display: 'inline', marginRight: 4 }} />Doctor&rsquo;s written findings</label>
                <textarea className="form-textarea" rows={4} value={finding} onChange={(e) => setFinding(e.target.value)} placeholder="Describe what you observe. Only this human-written note is saved to the EMR." />
              </div>
              <button className="btn btn-secondary" disabled={busy} onClick={saveToRecord}>
                <FileCheck size={14} /> Save findings to medical record
              </button>
              {saved && <p style={{ color: 'var(--color-success)', fontSize: '0.85rem', marginTop: 10 }}>{saved}</p>}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
