import { useState } from 'react';
import { mockReports } from '../../data/mockData';
import { FileText, Download, Eye, Pill, Calendar, ChevronDown, ChevronUp } from 'lucide-react';

export default function MyReports() {
  const [expanded, setExpanded] = useState(null);

  const handleDownload = (report) => {
    const content = `ENT ENDOSCOPY SYSTEM - MEDICAL REPORT\n${'='.repeat(50)}\n\nPatient: Arjun Sharma\nDate: ${report.date}\nDoctor: ${report.doctorName}\n\nDIAGNOSIS\n${'-'.repeat(30)}\n${report.diagnosis}\n\nAI RESULT\nPrediction: ${report.aiResult.label}\nConfidence: ${(report.aiResult.confidence * 100).toFixed(1)}%\nSeverity: ${report.aiResult.severity}\n\nDOCTOR REMARKS\n${report.remarks}\n\nPRESCRIPTION\n${report.medicines.map(m => `• ${m.name} ${m.dosage} - ${m.frequency} for ${m.duration}`).join('\n')}\n\nFOLLOW-UP\n${report.followUp}\n\n${'='.repeat(50)}\nGenerated by ENT Scope Pro`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = `Report-${report.id}.txt`; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="animate-fadeIn">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
        <div>
          <h2 style={{ fontFamily: 'Outfit,sans-serif', fontWeight: 800, fontSize: '1.2rem' }}>My ENT Reports</h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.82rem' }}>{mockReports.length} reports on record</p>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <select className="form-select" style={{ width: 150 }}><option>All Reports</option><option>This Month</option><option>Last 3 Months</option></select>
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        {mockReports.map(r => (
          <div key={r.id} className="card" style={{ padding: 0, overflow: 'hidden' }}>
            {/* Report Header */}
            <div style={{ display: 'flex', alignItems: 'center', gap: 16, padding: '18px 24px', cursor: 'pointer' }} onClick={() => setExpanded(expanded === r.id ? null : r.id)}>
              <div style={{ width: 48, height: 48, borderRadius: 14, background: '#eff6ff', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                <FileText size={22} color="#2563eb" />
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ fontWeight: 700, fontSize: '1rem', color: 'var(--text-primary)', marginBottom: 2 }}>{r.diagnosis}</div>
                <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{r.date} · {r.doctorName}</div>
                <div style={{ marginTop: 6, display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                  <span className={`badge ${r.aiResult.severity === 'Mild' ? 'badge-green' : r.aiResult.severity === 'Moderate' ? 'badge-yellow' : 'badge-red'}`}>{r.aiResult.severity}</span>
                  <span className="badge badge-blue">AI: {r.aiResult.label} ({(r.aiResult.confidence*100).toFixed(0)}%)</span>
                </div>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <button className="btn btn-sm btn-outline" onClick={e => { e.stopPropagation(); handleDownload(r); }}>
                  <Download size={14} /> Download
                </button>
                {expanded === r.id ? <ChevronUp size={18} color="var(--text-muted)" /> : <ChevronDown size={18} color="var(--text-muted)" />}
              </div>
            </div>

            {/* Expanded Details */}
            {expanded === r.id && (
              <div style={{ borderTop: '1px solid var(--border-color)', background: 'var(--bg-hover)', padding: '20px 24px', display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 20 }} className="animate-slideUp">
                <div>
                  <div style={{ fontWeight: 700, fontSize: '0.78rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: 8, display: 'flex', alignItems: 'center', gap: 6 }}>
                    <Eye size={13} /> Doctor Remarks
                  </div>
                  <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: 1.6 }}>{r.remarks}</p>
                </div>
                <div>
                  <div style={{ fontWeight: 700, fontSize: '0.78rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: 8, display: 'flex', alignItems: 'center', gap: 6 }}>
                    <Pill size={13} /> Prescription
                  </div>
                  {r.medicines.map((m, i) => (
                    <div key={i} style={{ background: 'var(--bg-card)', borderRadius: 8, padding: '8px 12px', marginBottom: 6 }}>
                      <div style={{ fontWeight: 600, fontSize: '0.85rem' }}>{m.name} <span style={{ color: 'var(--text-muted)', fontWeight: 400 }}>{m.dosage}</span></div>
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{m.frequency} · {m.duration}</div>
                    </div>
                  ))}
                </div>
                <div>
                  <div style={{ fontWeight: 700, fontSize: '0.78rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: 8, display: 'flex', alignItems: 'center', gap: 6 }}>
                    <Calendar size={13} /> Follow-Up
                  </div>
                  <div style={{ background: '#eff6ff', border: '1px solid #2563eb20', borderRadius: 10, padding: 12 }}>
                    <div style={{ fontWeight: 700, fontSize: '1rem', color: '#2563eb' }}>{r.followUp}</div>
                    <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', marginTop: 2 }}>Scheduled follow-up visit</div>
                  </div>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      {mockReports.length === 0 && (
        <div className="card" style={{ textAlign: 'center', padding: 60 }}>
          <FileText size={40} color="var(--text-muted)" style={{ margin: '0 auto 12px' }} />
          <p style={{ color: 'var(--text-muted)' }}>No reports available yet.</p>
        </div>
      )}
    </div>
  );
}
